In [110]:
# task_1 //
import numpy as np
Z = np.diag(np.arange(1, 5), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [111]:
# task_2 //
arr = np.random.random((10, 3))
print(arr)
    
(0.5 + np.min(np.fabs(arr-0.5), axis = 1))[np.min(arr -0.5, axis = 1) != np.min(np.fabs(arr-0.5), axis = 1)]

# (0.5 + np.min(np.fabs(arr-0.5), axis = 1))

# 0.5 + np.min(arr -0.5, axis = 1) != 0.5 + np.min(np.fabs(arr-0.5), axis = 1)

[[0.40189165 0.33490258 0.77247114]
 [0.84359209 0.95995709 0.72701015]
 [0.98560034 0.22463415 0.62579453]
 [0.90616813 0.61317059 0.2920512 ]
 [0.84511031 0.0122381  0.6214142 ]
 [0.77991332 0.23545006 0.73249342]
 [0.97246642 0.69801549 0.34541064]
 [0.01400252 0.06488156 0.14222692]
 [0.26390903 0.65355    0.57295983]
 [0.30211264 0.85264422 0.62195093]]


array([0.59810835, 0.62579453, 0.61317059, 0.6214142 , 0.73249342,
       0.65458936, 0.85777308, 0.57295983, 0.62195093])

In [112]:
# task_3 //
arr = np.random.random((6, 6))
np.sum(arr, axis = 1)/np.max(arr, axis = 1)

array([3.3738138 , 2.2726294 , 4.19378438, 3.795592  , 2.97650172,
       4.44492683])

In [113]:
# task_4
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max(x[(np.argwhere(x == 0)+1)%x.shape])

6

In [114]:
# task_5 //

x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x[np.unique(i, return_counts = True)[0]] = x[np.unique(i, return_counts = True)[0]] + np.unique(i, return_counts = True)[1] 
# np.unique(i, return_counts = True)
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])

In [115]:
# task_6 //
x = 1.235
round(x), int(x), np.floor(x)

(1, 1, 1.0)

In [102]:
from sklearn.datasets import fetch_openml

images, labels = fetch_openml('mnist_784', return_X_y=True, as_frame=False)

In [116]:
# task_7 //
import numpy as np
def kNN(train_X, train_Y ,test_X, k=8):
    res = []
    test_Y = []
    for i in test_X:
        res = np.argsort(np.linalg.norm(train_X - i, axis=1))[:k]
        numberOftrain = np.argmax(np.unique(train_Y[res],  return_counts = True)[1])
        test_Y.append(np.unique(train_Y[res],  return_counts = True)[0][numberOftrain])
        
        
    
    return test_Y

sizeOfSampleTrain = 20
sizeOfSampleTest = 5
cluster = 4
neighbors = 3

train_X = np.random.random((sizeOfSampleTrain, 2))
train_Y = np.random.randint(cluster, size = sizeOfSampleTrain)
test_X = np.random.random((sizeOfSampleTest, 2))
print(kNN(train_X, train_Y ,test_X))

[1, 1, 1, 1, 0]


In [119]:
# task_8 //
import numpy as np
def kNN(train_X, train_Y ,test_X, k):
    res = []
    test_Y = []
    for i in test_X:
        res = np.argsort(np.linalg.norm(train_X - i, axis=1))[:k]
        numberOftrain = np.argmax(np.unique(train_Y[res],  return_counts = True)[1])
        test_Y.append(np.unique(train_Y[res],  return_counts = True)[0][numberOftrain])
        
        
    
    return test_Y

sample_result =[]


train_size = 1000
train_images = images[:train_size]
train_labels = labels[:train_size]
test_size = 100
test_images = images[-test_size:]
test_labels = labels[-test_size:]


np.sum(test_labels == kNN(train_images, train_labels ,test_images, 8))/test_size


# for i in range (5, 20):
#     sample_result.append(np.sum(test_labels == kNN(train_images, train_labels ,test_images, i)))
# print(sample_result) 

0.87